# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Yuexi's Blog 月茜的博客"
email: tanyuexi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tan Yuexi's personal blog <br>
  谭月茜的个人博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tanyuexi.github.io" # the base hostname & protocol for your site
twitter_username:  YuexiTan
github_username:  tanyuexi
linkedin_username:  yuexitan

# Build settings
markdown: kramdown
exclude: [.DS_Store,run_test.sh,.git,.gitignore,.sass-cache]
encoding: utf-8
